@startuml
actor 专家用户
participant 个人中心页面
participant PersonalController
participant PersonalService
participant PersonalDao
专家用户->个人中心页面:进入界面
activate 个人中心页面
个人中心页面->PersonalController:查询未回复的消息列表
activate PersonalController
PersonalController->PersonalService:查询消息列表
activate PersonalService
PersonalService->PersonalDao:查询消息列表
activate PersonalDao
PersonalDao-->PersonalService:返回消息列表
deactivate PersonalDao
PersonalService-->PersonalController:获得消息列表
deactivate PersonalService
PersonalController-->个人中心页面:获得消息列表
deactivate PersonalController
个人中心页面-->专家用户:显示消息列表
deactivate 个人中心页面

专家用户->个人中心页面:点击要回复的消息
activate 个人中心页面
专家用户->个人中心页面:点击是否参加
个人中心页面->PersonalController:得到回复消息参数
activate PersonalController
PersonalController->PersonalService:得到回复消息参数
activate PersonalService
PersonalService->PersonalDao:根据消息id修改状态
activate PersonalDao
PersonalService->PersonalDao:根据抽取结果id和专家id修改状态
PersonalDao-->PersonalService:返回修改状态
deactivate PersonalDao
PersonalService-->PersonalController:返回修改状态
deactivate PersonalService
PersonalController-->个人中心页面:返回修改状态
deactivate PersonalController
个人中心页面-->专家用户:重新显示消息列表
deactivate 个人中心页面
@enduml