@startuml
actor 管理员
participant 角色列表页面
participant RolePermissionController
participant RolePermissionService
participant RolePermissionDao
管理员->角色列表页面:进入界面
activate 角色列表页面
角色列表页面->RolePermissionController:要修改权限的角色id
activate RolePermissionController
RolePermissionController->RolePermissionService:角色id
activate RolePermissionService
RolePermissionService->RolePermissionDao:根据角色id查询权限资源
activate RolePermissionDao
RolePermissionService->RolePermissionService:权限资源树形处理
RolePermissionDao-->RolePermissionService:返回该角色的权限资源
deactivate RolePermissionDao
RolePermissionService-->RolePermissionController:获得权限列表树形结构
deactivate RolePermissionService
RolePermissionController-->角色列表页面:获得权限列表
deactivate RolePermissionController
角色列表页面-->管理员:显示角色权限
deactivate 角色列表页面

管理员->角色列表页面:选项拥有的权限
activate 角色列表页面
管理员->角色列表页面:点击更新权限
角色列表页面->RolePermissionController:得到新的权限列表和角色id
activate RolePermissionController
RolePermissionController->RolePermissionService:新权限id集合和角色id
activate RolePermissionService
RolePermissionService->RolePermissionDao:根据角色id删除老权限
activate RolePermissionDao
RolePermissionService->RolePermissionDao:根据角色id和新权限id集合添加权限
RolePermissionDao-->RolePermissionService:返回删除情况和添加情况
deactivate RolePermissionDao
RolePermissionService-->RolePermissionController:返回删除情况和添加情况
deactivate RolePermissionService
RolePermissionController-->角色列表页面:返回删除情况和添加情况
deactivate RolePermissionController
角色列表页面-->管理员:显示修改成功
deactivate 角色列表页面
@enduml