@startuml
actor 管理员
participant 专家抽取页面
participant ExpertExtractionController
participant ExpertExtractionService
participant ExpertExtractionDao
管理员->专家抽取页面:进入界面
activate 专家抽取页面
专家抽取页面->ExpertExtractionController:查询所有项目信息
activate ExpertExtractionController
ExpertExtractionController->ExpertExtractionService:
activate ExpertExtractionService
ExpertExtractionService->ExpertExtractionDao:查询全部项目
activate ExpertExtractionDao
ExpertExtractionDao-->ExpertExtractionService:返回查询到数据
deactivate ExpertExtractionDao
ExpertExtractionService-->ExpertExtractionController:获得项目信息
deactivate ExpertExtractionService
ExpertExtractionController-->专家抽取页面:获得项目列表
deactivate ExpertExtractionController
专家抽取页面-->管理员:显示项目列表
deactivate 专家抽取页面

管理员->专家抽取页面:选择项目
activate 专家抽取页面
专家抽取页面->ExpertExtractionController:得到项目id
activate ExpertExtractionController
ExpertExtractionController->ExpertExtractionService:项目id
activate ExpertExtractionService
ExpertExtractionService->ExpertExtractionDao:根据项目id查询信息
activate ExpertExtractionDao
ExpertExtractionDao-->ExpertExtractionService:返回项目信息
deactivate ExpertExtractionDao
ExpertExtractionService-->ExpertExtractionController:返回项目信息
deactivate ExpertExtractionService
ExpertExtractionController-->专家抽取页面:返回项目信息
deactivate ExpertExtractionController
专家抽取页面-->管理员:显示项目信息
deactivate 专家抽取页面

管理员->专家抽取页面:选择筛选条件
activate 专家抽取页面
专家抽取页面->ExpertExtractionController:得到抽取条件
activate ExpertExtractionController
ExpertExtractionController->ExpertExtractionService:抽取条件
activate ExpertExtractionService
ExpertExtractionService->ExpertExtractionDao:根据抽取条件查询专家
activate ExpertExtractionDao
ExpertExtractionDao-->ExpertExtractionService:返回专家列表
ExpertExtractionService-->ExpertExtractionService:随机抽取专家
ExpertExtractionService->ExpertExtractionDao:修改项目信息
ExpertExtractionService->ExpertExtractionDao:向专家发送抽取消息
deactivate ExpertExtractionDao
ExpertExtractionService-->ExpertExtractionController:返回专家列表
deactivate ExpertExtractionService
ExpertExtractionController-->专家抽取页面:返回专家列表
deactivate ExpertExtractionController
专家抽取页面-->管理员:显示抽取结果
deactivate 专家抽取页面
@enduml