@startuml
actor 管理员
participant 项目信息页面
participant ProjectController
participant ProjectService
participant ProjectDao
管理员->项目信息页面:进入界面
activate 项目信息页面
项目信息页面->ProjectController:分页查询所有项目信息
activate ProjectController
ProjectController->ProjectService:当前页数和显示条数
activate ProjectService
ProjectService->ProjectDao:查询全部项目
activate ProjectDao
ProjectDao-->ProjectService:返回查询到数据
deactivate ProjectDao
ProjectService-->ProjectController:获得项目信息
deactivate ProjectService
ProjectController-->项目信息页面:获得项目信息
deactivate ProjectController
项目信息页面-->管理员:分页显示项目信息
deactivate 项目信息页面

管理员->项目信息页面:点击删除专家
activate 项目信息页面
项目信息页面->ProjectController:得到删除的项目id
activate ProjectController
ProjectController->ProjectService:项目id
activate ProjectService
ProjectService->ProjectDao:根据项目id删除信息
activate ProjectDao
ProjectDao-->ProjectService:返回删除情况
deactivate ProjectDao
ProjectService-->ProjectController:返回删除情况
deactivate ProjectService
ProjectController-->项目信息页面:返回删除情况
deactivate ProjectController
项目信息页面-->管理员:显示删除情况
deactivate 项目信息页面
@enduml