@startuml
actor 管理员
participant 用户列表页面
participant UsersController
participant UsersService
participant UsersDao
管理员->用户列表页面:点击添加用户
activate 用户列表页面
管理员->用户列表页面:填写用户名
用户列表页面->UsersController:获取用户名
activate UsersController
UsersController->UsersService:用户名
activate UsersService
UsersService->UsersDao:根据用户名查重
activate UsersDao
UsersDao-->UsersService:返回是否重复
deactivate UsersDao
UsersService-->UsersController:返回是否重复
deactivate UsersService
UsersController-->用户列表页面:返回是否重复
deactivate UsersController
用户列表页面-->管理员:显示是否重复
deactivate 用户列表页面

管理员->用户列表页面:点击确定
activate 用户列表页面
用户列表页面->UsersController:获取用户信息
activate UsersController
UsersController->UsersService:获取用户信息
activate UsersService
UsersService->UsersDao:新增用户
activate UsersDao
UsersService->UsersDao:新增用户角色关系
UsersDao-->UsersService:返回新增情况
deactivate UsersDao
UsersService-->UsersController:返回新增情况
deactivate UsersService
UsersController-->用户列表页面:返回新增情况
deactivate UsersController
用户列表页面-->管理员:显示新增情况
deactivate 用户列表页面
@enduml